import { Path } from '@/hooks/useSites';

export const getDefaultPaths = (siteName: string, siteCoords: { lat: number; lng: number }): Path[] => {
  return [
    {
      type: 'elderly',
      label: '👴 Accessible Path',
      difficulty: 'Easy',
      distance: '1-2 km',
      duration: '1-1.5 hours',
      description: 'Slow-paced, wheelchair-accessible route. Rest areas every 200m. No steep climbs.',
      waypoints: [
        {
          name: `${siteName} Entrance`,
          lat: siteCoords.lat,
          lng: siteCoords.lng,
          dist: '0 km',
          time: '0 min',
        },
        {
          name: 'Rest Area 1',
          lat: siteCoords.lat + 0.005,
          lng: siteCoords.lng + 0.005,
          dist: '0.5 km',
          time: '15 min',
        },
        {
          name: `${siteName} Main Temple`,
          lat: siteCoords.lat + 0.008,
          lng: siteCoords.lng + 0.008,
          dist: '1 km',
          time: '30 min',
        },
        {
          name: 'Rest Area 2 + Water',
          lat: siteCoords.lat + 0.012,
          lng: siteCoords.lng + 0.012,
          dist: '1.5 km',
          time: '45 min',
        },
        {
          name: 'Viewing Platform',
          lat: siteCoords.lat + 0.015,
          lng: siteCoords.lng + 0.015,
          dist: '2 km',
          time: '60 min',
        },
      ],
      amenities: [
        'Wheelchair accessible',
        'Rest benches every 200m',
        'Drinking water stations',
        'Toilet facilities',
        'Medical assistance available',
      ],
    },
    {
      type: 'adventure',
      label: '🧗 Adventure Trek',
      difficulty: 'Challenging',
      distance: '8-12 km',
      duration: '4-6 hours',
      elevation: '+500m / -500m',
      description: 'Full trekking experience. Rocky terrain, forest paths, panoramic viewpoints. Expert hikers only.',
      waypoints: [
        {
          name: `${siteName} Base Camp`,
          lat: siteCoords.lat,
          lng: siteCoords.lng,
          dist: '0 km',
          time: '0 min',
        },
        {
          name: 'Forest Trail Start',
          lat: siteCoords.lat + 0.01,
          lng: siteCoords.lng + 0.01,
          dist: '2 km',
          time: '45 min',
        },
        {
          name: 'First Ridge View',
          lat: siteCoords.lat + 0.02,
          lng: siteCoords.lng + 0.02,
          dist: '4 km',
          time: '100 min',
        },
        {
          name: 'Summit Rest Point',
          lat: siteCoords.lat + 0.025,
          lng: siteCoords.lng + 0.025,
          dist: '6 km',
          time: '150 min',
        },
        {
          name: 'Sacred Peak',
          lat: siteCoords.lat + 0.03,
          lng: siteCoords.lng + 0.03,
          dist: '8 km',
          time: '200 min',
        },
        {
          name: `${siteName} Summit Temple`,
          lat: siteCoords.lat + 0.035,
          lng: siteCoords.lng + 0.035,
          dist: '10 km',
          time: '240 min',
        },
        {
          name: 'Panoramic Lookout',
          lat: siteCoords.lat + 0.04,
          lng: siteCoords.lng + 0.04,
          dist: '12 km',
          time: '300 min',
        },
      ],
      amenities: [
        'Adventure experience',
        'Forest immersion',
        'Meditation spots',
        'Photography locations',
        'Experienced guides recommended',
      ],
    },
  ];
};
